# Generated by Django 4.2.10 on 2024-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSmartlyApp', '0002_alter_pointofinterest_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
