# Generated by Django 4.2.10 on 2024-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchSmartlyApp', '0004_alter_pointofinterest_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='internal_id',
            field=models.CharField(max_length=255),
        ),
    ]
